[program:cryptoinfo-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/cryptoinfo/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/cryptoinfo-queue.log
stopwaitsecs=3600

[program:cryptoinfo-scheduler]
process_name=%(program_name)s
command=php /var/www/cryptoinfo/artisan schedule:work
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/cryptoinfo-scheduler.log

[program:cryptoinfo-reverb]
process_name=%(program_name)s
command=php /var/www/cryptoinfo/artisan reverb:start --host=127.0.0.1 --port=8080
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/cryptoinfo-reverb.log
